apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-01-15T15:00:04Z"
  generateName: webapp-mysql-6bc4d8684c-
  generation: 1
  labels:
    name: webapp-mysql
    pod-template-hash: 6bc4d8684c
  name: webapp-mysql-6bc4d8684c-m4f4p
  namespace: triton
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: webapp-mysql-6bc4d8684c
    uid: d261e78f-115c-4f25-9f8d-c886ed7e1280
  resourceVersion: "4207"
  uid: 722b948f-195b-4dee-bfbc-91689f6554f1
spec:
  containers:
  - env:
    - name: DB_Host
      value: mysql
    - name: DB_User
      value: root
    - name: DB_Password
      value: paswrd
    image: mmumshad/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp-mysql
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cd8hh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-cd8hh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-01-15T15:39:45Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-01-15T15:39:41Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-01-15T15:39:45Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-01-15T15:39:45Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-01-15T15:39:40Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6158e9b11278c6c68f8284488990b0a35f518dba5df1383e1011d043d70f2da9
    image: docker.io/mmumshad/simple-webapp-mysql:latest
    imageID: docker.io/mmumshad/simple-webapp-mysql@sha256:d4d0c03fcb76cee6ae2511fa7f3f6b7090f0c5e0cb3f276687f9ddf2c689cc09
    lastState: {}
    name: webapp-mysql
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-01-15T15:39:44Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cd8hh
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.121.68
  hostIPs:
  - ip: 192.168.121.68
  observedGeneration: 1
  phase: Running
  podIP: 10.32.0.2
  podIPs:
  - ip: 10.32.0.2
  qosClass: BestEffort
  startTime: "2026-01-15T15:39:41Z"