apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-01-15T15:00:04Z"
  name: mysql
  namespace: triton
  resourceVersion: "940"
  uid: 5d693ee7-a11d-4415-bb84-7d9009dc6c73
spec:
  clusterIP: 10.108.88.115
  clusterIPs:
  - 10.108.88.115
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}