apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend-app
  name: frontend-svc
  namespace: default
spec:
  clusterIP: 172.20.205.196
  clusterIPs:
  - 172.20.205.196
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: frontend-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}