apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2026-01-12T13:08:47Z"
  generation: 1
  name: globals.traffic.controller
  resourceVersion: "910"
  uid: 3c954f38-c0d9-4095-ba7f-053798a7eb15
spec:
  conversion:
    strategy: None
  group: traffic.controller
  names:
    kind: Global
    listKind: GlobalList
    plural: globals
    shortNames:
    - gb
    singular: global
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              access:
                type: boolean
              dataField:
                type: integer
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: Global
    listKind: GlobalList
    plural: globals
    shortNames:
    - gb
    singular: global
  conditions:
  - lastTransitionTime: "2026-01-12T13:08:47Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2026-01-12T13:08:47Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1